#This config file is to set up CML platform for CI/CD on github for ML models.

name: model-training
on: [push]
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - uses: iterative/setup-cml@v1
      - name: Train model
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          pip3 install -r requirements.txt
          python3 src/main.py --Train true 

          cat metrics.txt >> report.md
          cml publish plot.png --md >> report.md
          cml send-comment report.md