#This config file is to set up CML platform for CI/CD on github for ML models.

name: CML & DVC
on: [push]
jobs:
  run:
    runs-on: ubuntu-latest
    container: docker://ghcr.io/iterative/cml:0-dvc2-base1
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Set up DVC on Google Drive
        env:
          GDRIVE_CREDENTIALS_DATA: ${{ secrets.GDRIVE_CREDENTIALS_DATA }}
        run: |
          cml ci --unshallow
          dvc remote add --default remote-gd gdrive://1FS1lBYuTH0cps2y7SQKkiDJZ9TIoyWa4
          dvc remote list #Shows the remote options
          dvc pull --remote remote-gd
      - name: Train model
        env: 
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cml ci --unshallow
          pip install -r requirements.txt  # Install dependencies
          python3 src/main.py --Train true
